repos:
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: clang-format
    args: ["-style=file", "-i"]
  - id: clang-tidy
    args: ["-p=./build_debug/compile_commands.json"]
  - id: cppcheck
  - id: cpplint
    args: ["--filter=-build/include_order,
           -whitespace/indent, -whitespace/comments"]
    files: '\.cpp$|\.hpp$|\.inl$'
